main: org.winlogon.simplertp.SimpleRTP
name: SimpleRTP
version: "0.1.0"
api-version: "1.21"
author: winlogon
description: Teleport to a random place, safely
commands:
  rtp:
    description: "SimpleRTP :: Teleport to a random place, safely."
    usage: "Usage: /rtp"
    aliases: randomteleport
permissions:
  rtp.*:
    default: true
