main: org.winlogon.simplertp.SimpleRtp
name: SimpleRtp
version: "0.1.0"
api-version: "1.21.1"
author: winlogon
description: Teleport to a random place, safely
commands:
  rtp:
    description: "Random teleport :: Teleport to a random place"
    usage: "Usage: /rtp [optional: range], example: /rtp 50000"
    aliases: randomteleport
permissions:
  rtp.*:
    default: true
