name: Test and Release

on:
  push:
    branches:
      - 'main'
  schedule:
    # PaperMC doesn't change version numbers for latest releases meaning the build may break
    #   unexpectedly. Build every so often so that we know if a breaking change has been published
    - cron: '0 0 * * 6'

jobs:
  test:
    name: Run unit tests
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        java: [ 21 ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Common Setup
        uses: ./.github/actions/common-setup
        with:
          java-version: ${{ matrix.java }}

      - name: Build with Gradle
        run: ./gradlew build --info